### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lukashes** [imanel/websocket-eventmachine-client#19]
Hi! The last release was in 2016. Could you create new release based at HEAD of master.

**Comment by clergyman** [comment]
For this reason the latest gem version does not send SNI on wss connection, although the code is already there and working fine

**Comment by imanel** [comment]
It's been a while since I took a look at this gem. Just released v1.3.0, hopefully it will help.

**Comment by clergyman** [comment]
Just checked with 1.3.0 release, everything is fine now, suppose we the can close the case now
@imanel thank you so much!
