### ISSUE TITLE
Assertion `EmConnsHash != ((VALUE)RUBY_Qnil)' failed.

### ISSUE THREAD

**Issue by Zloy** [imanel/websocket-eventmachine-client#9]
This simple test works when `Machine == EventMachine`, but doesn't when `Machine == WebSocket::EventMachine`

    #!/usr/bin/env ruby

    require 'rubygems'
    require 'bundler/setup'
    require "websocket-eventmachine-server"

    #Machine = EventMachine
    Machine = WebSocket::EventMachine
    Machine.run {}

It reports the error:

    ruby: rubymain.cpp:209: VALUE t_initialize_event_machine(VALUE): Assertion `EmConnsHash !=\
    ((VALUE)RUBY_Qnil)' failed.

My Gemfile

    source 'https://rubygems.org'
    gem 'websocket-eventmachine-server'

My Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        eventmachine (1.0.7)
        websocket (1.2.1)
        websocket-eventmachine-base (1.1.0)
          eventmachine (~> 1.0)
          websocket (~> 1.0)
          websocket-native (~> 1.0)
        websocket-eventmachine-server (1.0.1)
          websocket-eventmachine-base (~> 1.0)
        websocket-native (1.0.0)

    PLATFORMS
      ruby

    DEPENDENCIES
      websocket-eventmachine-server

**Comment by imanel** [comment]
It looks like it's [EventMachine](https://github.com/eventmachine/eventmachine) problem as [trace points](https://github.com/eventmachine/eventmachine/blob/master/ext/rubymain.cpp#L209). I'm not sure if I will be able to help.
